// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package constants

import (
	"errors"
	"fmt"
)

const (
	// AccountStatusACTIVE is a AccountStatus of type ACTIVE.
	AccountStatusACTIVE AccountStatus = "ACTIVE"
	// AccountStatusBLACKLISTED is a AccountStatus of type BLACKLISTED.
	AccountStatusBLACKLISTED AccountStatus = "BLACKLISTED"
	// AccountStatusCLOSED is a AccountStatus of type CLOSED.
	AccountStatusCLOSED AccountStatus = "CLOSED"
)

var ErrInvalidAccountStatus = errors.New("not a valid AccountStatus")

// String implements the Stringer interface.
func (x AccountStatus) String() string {
	return string(x)
}

// String implements the Stringer interface.
func (x AccountStatus) IsValid() bool {
	_, err := ParseAccountStatus(string(x))
	return err == nil
}

var _AccountStatusValue = map[string]AccountStatus{
	"ACTIVE":      AccountStatusACTIVE,
	"BLACKLISTED": AccountStatusBLACKLISTED,
	"CLOSED":      AccountStatusCLOSED,
}

// ParseAccountStatus attempts to convert a string to a AccountStatus.
func ParseAccountStatus(name string) (AccountStatus, error) {
	if x, ok := _AccountStatusValue[name]; ok {
		return x, nil
	}
	return AccountStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidAccountStatus)
}
