// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package constants

import (
	"errors"
	"fmt"
)

const (
	// BalanceOperationINCREASE is a BalanceOperation of type INCREASE.
	BalanceOperationINCREASE BalanceOperation = "INCREASE"
	// BalanceOperationDECREASE is a BalanceOperation of type DECREASE.
	BalanceOperationDECREASE BalanceOperation = "DECREASE"
)

var ErrInvalidBalanceOperation = errors.New("not a valid BalanceOperation")

// String implements the Stringer interface.
func (x BalanceOperation) String() string {
	return string(x)
}

// String implements the Stringer interface.
func (x BalanceOperation) IsValid() bool {
	_, err := ParseBalanceOperation(string(x))
	return err == nil
}

var _BalanceOperationValue = map[string]BalanceOperation{
	"INCREASE": BalanceOperationINCREASE,
	"DECREASE": BalanceOperationDECREASE,
}

// ParseBalanceOperation attempts to convert a string to a BalanceOperation.
func ParseBalanceOperation(name string) (BalanceOperation, error) {
	if x, ok := _BalanceOperationValue[name]; ok {
		return x, nil
	}
	return BalanceOperation(""), fmt.Errorf("%s is %w", name, ErrInvalidBalanceOperation)
}
