// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package constants

import (
	"errors"
	"fmt"
)

const (
	// ContextKeyWorkflowLogger is a ContextKey of type workflow_logger.
	ContextKeyWorkflowLogger ContextKey = "workflow_logger"
	// ContextKeyWorkflowReferenceId is a ContextKey of type workflow_reference_id.
	ContextKeyWorkflowReferenceId ContextKey = "workflow_reference_id"
)

var ErrInvalidContextKey = errors.New("not a valid ContextKey")

// String implements the Stringer interface.
func (x ContextKey) String() string {
	return string(x)
}

// String implements the Stringer interface.
func (x ContextKey) IsValid() bool {
	_, err := ParseContextKey(string(x))
	return err == nil
}

var _ContextKeyValue = map[string]ContextKey{
	"workflow_logger":       ContextKeyWorkflowLogger,
	"workflow_reference_id": ContextKeyWorkflowReferenceId,
}

// ParseContextKey attempts to convert a string to a ContextKey.
func ParseContextKey(name string) (ContextKey, error) {
	if x, ok := _ContextKeyValue[name]; ok {
		return x, nil
	}
	return ContextKey(""), fmt.Errorf("%s is %w", name, ErrInvalidContextKey)
}
